iptweb/iptsite/accounts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register$', views.register, name='register'),
    url(r'^authentication/$', views.manage_authentication, name='manage_authentication'),
    url(r'^register/$', views.register, name='register'),
    url(r'^registration-successful/$', views.registration_successful, name='registration_successful'),
    url(r'^password-reset/(?:(?P<code>.+)/)?$', views.password_reset, name='password_reset'),
    url(r'^activate/(?:(?P<code>.+)/)?$', views.email_confirmation, name='email_confirmation'),
    # url(r'^departments\.json$', views.departments_json, name='departments_json'),
]

iptweb/iptsite/urls.py
from django.conf.urls import include, url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^history$', views.history, name='history'),
    url(r'^run$', views.run, name='run'),
    url(r'^help$', views.help, name='help'),
    url(r'^compile$', views.compile, name='compile'),
    url(r'^terminal$', views.terminal, name='terminal'),
    url(r'^webterm$', views.webterm, name='webterm'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^create_account$', views.create_account, name='create_account'),
    url(r'^accounts/', include('iptsite.accounts.urls', namespace='accounts')),
    url(r'^admin$', views.admin, name='admin'),
    url(r'^download/(?P<path>.*)/?$', views.download, name='download'),
    url(r'^upload?$', views.upload, name='upload'),
    url(r'^$', views.login, name='login'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

iptweb/iptweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from iptsite.forms import LoginForm
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('iptsite.urls')),
    #  r'^accounts/login/$', auth_views.login, name='login'
     url(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='iptsite/login.html')),
    # url('^', include('django.contrib.auth.urls'), {'template_name': 'login.html', 'authentication_form': LoginForm}),
    url(r'^logout/$', views.logout, {'next_page': '/login'}),

]

iptweb/iptsite/forms.py
# iptsite/forms.py

from django.contrib.auth.forms import AuthenticationForm
from django import forms

# If you don't do this you cannot use Bootstrap CSS
class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'password'}))

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

iptweb/iptsite/accounts/views.py
from django.shortcuts import render
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render_to_response
from django.utils.translation import ugettext_lazy as _
from . import forms

from pytas.http import TASClient
from pytas.models import User as TASUser
import logging
import json
import re

logger = logging.getLogger(__name__)


@login_required
def manage_authentication(request):
    if request.method == 'POST':
        form = forms.ChangePasswordForm(request.POST, username=request.user.username)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your TACC Password has been successfully changed!')
    else:
        form = forms.ChangePasswordForm(username=request.user.username)

    context = {
        'title': 'Authentication Settings',
        'form': form
    }
    return render(request, 'iptsite/accounts/manage_auth.html', context)


def register(request):
    if request.method == 'POST':
        account_form = forms.UserRegistrationForm(request.POST)
        if account_form.is_valid():
            try:
                account_form.save()
                return HttpResponseRedirect(
                    reverse('accounts:registration_successful'))
            except Exception as e:
                logger.info('error: {}'.format(e))

                error_type = e.args[1] if len(e.args) > 1 else ''

                if 'DuplicateLoginException' in error_type:
                    err_msg = (
                        'The username you chose has already been taken. Please '
                        'choose another. If you already have an account with TACC, '
                        'please log in using those credentials.')
                    account_form._errors.setdefault('username', [err_msg])
                elif 'DuplicateEmailException' in error_type:
                    err_msg = (
                        'This email is already registered. If you already have an '
                        'account with TACC, please log in using those credentials.')
                    account_form._errors.setdefault('email', [err_msg])
                    err_msg = '%s <a href="%s">Did you forget your password?</a>' % (
                        err_msg,
                        reverse('accounts:password_reset'))
                elif 'PasswordInvalidException' in error_type:
                    err_msg = (
                        'The password you provided did not meet the complexity '
                        'requirements.')
                    account_form._errors.setdefault('password', [err_msg])
                else:

                    safe_data = account_form.cleaned_data.copy()
                    safe_data['password'] = safe_data['confirmPassword'] = '********'
                    logger.exception('User Registration Error!', extra=safe_data)
                    err_msg = (
                        'An unexpected error occurred. If this problem persists '
                        'please create a support ticket.')
                messages.error(request, err_msg)
        else:
            messages.error(request, 'There were errors processing your registration. '
                                    'Please see below for details.')
    else:
        account_form = forms.UserRegistrationForm()

    context = {
        'account_form': account_form
    }
    return render(request, 'iptsite/accounts/register.html', context)


def registration_successful(request):
    return render_to_response('iptsite/accounts/registration_successful.html')


def password_reset(request, code=None):
    if code is None:
        code = request.GET.get('code', None)

    if code is not None:
        # confirming password reset
        message = 'Confirm your password reset using the form below. Enter your TACC ' \
                  'username and new password to complete the password reset process.'

        if request.method == 'POST':
            form = forms.PasswordResetConfirmForm(request.POST)
            if _process_password_reset_confirm(request, form):
                messages.success(request, 'Your password has been reset! You can now log '
                                          'in using your new password')
                return HttpResponseRedirect(reverse('terminal'))
            else:
                messages.error(request, 'Password reset failed. '
                                        'Please see below for details.')
        else:
            form = forms.PasswordResetConfirmForm(initial={'code': code})

    else:
        # requesting password reset
        message = 'Enter your TACC username to request a password reset. If your ' \
                  'account is found, you will receive an email at the registered email ' \
                  'address with instructions to complete the password reset.'

        if request.method == 'POST':
            form = forms.PasswordResetRequestForm(request.POST)
            if _process_password_reset_request(request, form):
                form = forms.PasswordResetRequestForm()
            else:
                messages.error(request, 'Password reset request failed. '
                                        'Please see below for details.')
        else:
            form = forms.PasswordResetRequestForm()

    return render(request, 'iptsite/accounts/password_reset.html',
                  {'message': message, 'form': form})


def _process_password_reset_request(request, form):
    if form.is_valid():
        # always show success to prevent data leaks
        messages.success(request, 'Your request has been received. If an account '
                                  'matching the username you provided is found, you will '
                                  'receive an email with further instructions to '
                                  'complete the password reset process.')

        username = form.cleaned_data['username']
        logger.info('Attempting password reset request for username: "%s"', username)
        try:
            tas = TASClient()
            user = tas.get_user(username=username)
            logger.info('Processing password reset request for username: "%s"', username)
            resp = tas.request_password_reset(user['username'], source='IPT')
            logger.debug(resp)
        except Exception as e:
            logger.exception('Failed password reset request')

        return True
    else:
        return False


def _process_password_reset_confirm(request, form):
    if form.is_valid():
        data = form.cleaned_data
        try:
            tas = TASClient()
            return tas.confirm_password_reset(data['username'], data['code'],
                                              data['password'], source='IPT')
        except Exception as e:
            if len(e.args) > 1:
                if re.search('account does not match', e.args[1]):
                    form.add_error('username', e.args[1])
                elif re.search('No password reset request matches', e.args[1]):
                    form.add_error('code', e.args[1])
                elif re.search('complexity requirements', e.args[1]):
                    form.add_error('password', e.args[1])
                elif re.search('expired', e.args[1]):
                    form.add_error('code', e.args[1])
                else:
                    logger.exception('Password reset failed')
                    form.add_error('__all__', 'An unexpected error occurred. '
                                              'Please try again')
            else:
                form.add_error('__all__', 'An unexpected error occurred. '
                                          'Please try again')

    return False


def email_confirmation(request, code=None):
    context = {}
    if request.method == 'POST':
        form = forms.EmailConfirmationForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            code = data['code']
            username = data['username']
            password = data['password']
            try:
                tas = TASClient()
                user = tas.get_user(username=username)
                if tas.verify_user(user['id'], code, password=password):
                    messages.success(request,
                                     'Congratulations, your account has been activated! '
                                     'You can now log in to IPT.')
                    return HttpResponseRedirect(
                        reverse('terminal'))
                else:
                    messages.error(request,
                                   'We were unable to activate your account. Please try '
                                   'again.')
                    form = forms.EmailConfirmationForm(
                        initial={'code': code, 'username': username})
            except:
                logger.exception('TAS Account activation failed')
                form.add_error('__all__',
                               'Account activation failed. Please confirm your '
                               'activation code, username and password and try '
                               'again.')
    else:
        if code is None:
            code = request.GET.get('code', '')
        form = forms.EmailConfirmationForm(initial={'code': code})

    context['form'] = form

    return render(request, 'iptsite/accounts/email_confirmation.html', context)


# def departments_json(request):
#     institution_id = request.GET.get('institutionId')
#     if institution_id:
#         tas = TASClient()

iptweb/iptsite/templates/iptsite/admin.html
{% extends 'base.html' %}

{% block header %}
<h1>Current IPT Terminals</h1>
{% endblock %}
{% block headersum %}
{% endblock %}

{% block body %}
    {% if error %}
    <div class="error">
        <p>There was an error: {{ error }}</p>
    </div>
    {% endif %}
    <table class="table table-hover">
        <tr>
            <thead>
            <th>User</th>
            <th>Status</th>
            <th>URL</th>
            <th>Metadata UUID</th>
            <th>Metadata Key</th>
            <th>Action</th>
            </thead>
        </tr>
        {% for term in terminals %}
        <tr>
            <td>{{ term.user }}</td>
            <td>{{ term.status }}</td>
            <td>{{ term.url }}</td>
            <td>{{ term.uuid }}</td>
            <td>{{ term.name }}</td>
            <td>
            {% if term.action %}
            <form method="post" action="/admin">{% csrf_token %}
              <input type="hidden" class="form-control" name="user" value="{{ term.user }}">
                <input type="hidden" class="form-control" name="uuid" value="{{ term.uuid }}">
                <input type="hidden" class="form-control" name="command" value="{{ term.action }}">
                <input type="submit" value="{{ term.submit }}">
            </form>
            {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

iptweb/iptsite/templates/iptsite/compile.html
{% extends 'base.html' %}

{% block header %}
<h1>Launching a Compile Job</h1>
{% endblock %}

{% block headersum %}
<p>This form will guide you towards composing the command for compiling your serial or parallel programs on TACC/XSEDE resources. Please upload all the files that are external to your program but are required for compiling it successfully, such as, header files and other C/C++ program files.</p>
<p> The output from your jobs can be found in <strong>/home/ipt/jobs/{date}/compile-{system}-{job-id}</strong></p>
{% endblock %}

{% block body %}
<div id="compile" class="tab-pane fade in active">
    <div class="container">
        <form method="POST" action="/compile">{% csrf_token %}
            <div class="form-group">
                <label for="system">System:</label>
                <select class="form-control" id="system" name="system">
                {% for sys,val in systems.items %}
                  <option value={{sys}} {% if system == sys %}selected{% endif %}>{{val.display_name}}</option>
                {% endfor %}
                </select>
                {% if system_error %}
                <div class="error">
                    <p>There was an error: {{ system_error }}</p>
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="ccommand">Command:</label>
                <input type="ccommand" class="form-control" id="ccommand" placeholder="Enter $command"
                       name="ccommand" required>
                <!-- Table to display command input options -->
                <table class="table-condensed">
                    <thead>
                    <tr>
                        <th>If using</th>
                        <th>Enter</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>serial, C:</td>
                        <td>icc</td>
                    </tr>
                    <tr>
                        <td>serial, C++:</td>
                        <td>icpc</td>
                    </tr>
                    <tr>
                        <td>MPI, C:</td>
                        <td>mpicc</td>
                    </tr>
                    <tr>
                        <td>MPI, C++:</td>
                        <td>mpicxx</td>
                    </tr>
                    <tr>
                        <td>Open MP, C:</td>
                        <td>icc -qopenmp</td>
                    </tr>
                    <tr>
                        <td>Open MP, C++:</td>
                        <td>icpc -qopenmp</td>
                    </tr>
                    <tr>
                        <td>CUDA:</td>
                        <td>nvcc</td>
                    </tr>
                    </tbody>

                </table>
                <!-- Error handling -->
                {% if command_error %}
                <div class="error">
                    <p>There was an error: {{ command_error }}</p>
                </div>
                {% endif %}
                {% if compile_error %}
                <div class="error">
                    <p>There was an error: {{ compile_error }}</p>
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="driver">Driver:</label>
                <input type="driver" class="form-control" id="driver" name="driver" required>
                {% if driver_error %}
                <div class="error">
                    <p>There was an error: {{ driver_error }}</p>
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="outfiles">Output File(s):</label>
                <input type="outfiles" class="form-control" id="outfiles" placeholder="a.out" name="outfiles"
                       required>
                {% if outfiles_error %}
                <div class="error">
                    <p>There was an error: {{ outfiles_error }}</p>
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="addfiles">Additional Files:</label>
                <input type="addfiles" class="form-control" id="addfiles"
                       placeholder="Add additional files or folders separated by commas" name="addfiles">
            </div>
            <div class="form-group">
                <label for="modules">Modules:</label>
                <input type="modules" class="form-control" id="modules"
                       placeholder="Add modules to load separated by commas" name="modules">
               {% if modules_error %}
               <div class="error">
                   <p>There was an error: {{ modules }}</p>
               </div>
               {% endif %}
            </div>
            <div class="form-group">
                <label for="commargs">Command Args:</label>
                <!-- <input type="commargs" class="form-control" id="commargs" placeholder="$args" name="commargs"
                       required> -->
                <input type="commargs" class="form-control" id="commargs" placeholder="$args" name="commargs">
                {% if commargs_error %}
                <div class="error">
                    <p>There was an error: {{ commargs_error }}</p>
                </div>
                {% endif %}
            </div>
            <!-- <h4>This is your command:</h4>
            <p id="compileFullCommand"></p> -->

            <div class="text-right">
                <button type="submit" class="btn btn-default">Compile Code</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

iptweb/iptsite/templates/iptsite/help.html
{% extends 'base.html' %}
{% load static %}


        {% block body %}
        <!-- Help Tab -->
        <!--Section header-->
        <h2>Just Getting Started with IPT?</h2>
        <!--Links-->
        <h4><a href="https://diagrid.org/resources/ipt/about" target="_blank"
               alt="Interactive Parallelization Tool (IPT)">Interactive Parallelization Tool (IPT)</a></h4>

        <p>Interactive Parallelization Tool (IPT) is a high-level tool for transforming serial C/C++ applications
          into their parallel variants. The parallel programming models that are currently supported by IPT are:
          MPI, OpenMP, CUDA, and Hybrid Programming models. The end-users of IPT must have an understanding
          of the basic concepts involved in parallel programming (e.g., data distribution and data gathering).
          After developing an understanding of the basic parallel programming concepts,
          IPT can be used by its target audience (domain experts and students) to semi-automatically generate
          parallel programs based on multiple parallel programming paradigms (MPI, OpenMP, and CUDA), and
          learn about these paradigms through observation and comparison. The IPT-based personalized learning
          approach complements the traditional methods of learning and training that usually emphasize the syntax
          and semantics of one or more programming standards. IPT provides a jumpstart to the domain experts
          in using modern High Performance Computing (HPC) platforms for their research and development needs,
          and hence lowers the adoption barriers to HPC.</p>
        <h4>
          For further high-level details related to IPT (motivation, design, benefits), please review our
            <a href="http://dl.acm.org/citation.cfm?id=2616558" target="_blank" alt="A Tool for Interactive Parallelization">paper</a>.
        </h4>

        <!--Section header-->
        <h2>Want to Learn More?</h2>
        <!--Links-->
        <h4><a href="{% static 'supportdocs/trainingIPT.zip' %}" target="_blank" alt="Tutorial Files for IPT">Tutorial
            Files for IPT</a></h4>

        <p>Some test cases and the step-by-step process of parallelizing those test cases using IPT can be downloaded
        <a href={% static 'supportdocs/trainingIPT.zip' %} target="_blank" alt="IPT user guide">here</a>.</p>

        <h4><a href="{% static 'supportdocs/User_Guide_1.0.pdf' %}" target="_blank" alt="IPT user guide">IPT User
            Guide</a></h4>

        <h4>The usage of IPT is also demonstrated through the following videos:</h4>
        <h5>OpenMP Version of Molecular Dynamics Code Using the Interactive Parallelization Tool</h5>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/JH7o_k9Bxd0?rel=0" frameborder="0" allowfullscreen></iframe>
        <h5>Interactive Parallelization Tool - Parallelizing Molecular Dynamics with MPI</h5>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/HvlA4pnfFjE?rel=0" frameborder="0" allowfullscreen></iframe>
        <h5>The Interactive Parallelization Tool - Parallelizing the FFT Algorithm with CUDA</h5>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/kCOjqza7OG8?rel=0" frameborder="0" allowfullscreen></iframe>
        <h5>The Interactive Parallelization Tool - Parallelizing the FFT algorithm with OpenMP</h5>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/L4a19kF6q48?rel=0" frameborder="0" allowfullscreen></iframe>
        <h5>The Interactive Parallelization Tool - Parallelizing the FFT algorithm with MPI</h5>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/sg9HDTz0zbo?rel=0" frameborder="0" allowfullscreen></iframe>

        <!-- <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et
            dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>
        <h4><a href="https://www.youtube.com/watch?v=HvlA4pnfFjE" target="_blank"
               alt="Video demonstration of how to use Interactive Parallelization Tool - Parallelizing Molecular Dynamics with MPI">Interactive
            Parallelization Tool - Parallelizing Molecular Dynamics with MPI</a></h4> -->

        <!-- <p>This demo utilizes the interactive parallelization tool developed at TACC to pararallelize the Molecular
            Dynamics code. The beta version of this code is available on Diagrid.</p>
        <h4><a href="https://www.youtube.com/watch?v=L4a19kF6q48" target="_blank"
               alt="Video demonstration of how to use The Interactive Parallelization Tool - Parallelizing the FFT algorithm with OpenMP">The
            Interactive Parallelization Tool - Parallelizing the FFT algorithm with OpenMP</a></h4>

        <p>A brief walk-through on how to use this tool to transform a sequential program into a parallel one through a
            command line interface. In this demonstration, we will be parallelizing the Fast Fourier Transform Algorithm
            with OpenMP.</p> -->
        {% endblock %}

iptweb/iptsite/templates/iptsite/history.html
{% extends 'base.html' %}
  <!-- History Tab -->
  {% block header %}
  <h1>Your Job History</h1>
  {% endblock %}

  {% block body %}
        <table class="table table-hover">
            <tr>
                <thead>
                <th>ID</th>
                <th>Name</th>
                <th>Status</th>
                <th>Start</th>
                <th>End</th>
                </thead>
            </tr>
            {% for job in jobs %}
            <tr>
                <td>{{ job.id }}</td>
                <td>{{ job.name }}</td>
                <td>{{ job.status }}</td>
                <td>{{ job.startTime }}</td>
                <td>{{ job.endTime }}</td>
                <td></td>
            </tr>
            {% endfor %}
        </table>
</div>
{% endblock %}

iptweb/iptsite/templates/iptsite/login.html
<!-- User Login page -->
{% extends 'base.html' %}

{% load staticfiles %}

{% block body %}

<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    <center>Welcome to IPT</center>
                </h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="POST" action="/login">{% csrf_token %}
                    <fieldset>
                        <legend>Sign In to IPT</legend>
                        <div class="form-group">
                            <label for="username" class="col-lg-2 control-label"></label>

                            <div class="col-lg-8">
                                <input type="username" class="form-control" id="username" placeholder="Enter Username"
                                       name="username">
                            </div>
                        </div>
                        <!-- Original -->
                        <div class="form-group">
                            <label for="password" class="col-lg-2 control-label"></label>

                            <div class="col-lg-8">
                                <input type="password" class="form-control" id="password" placeholder="Enter Password"
                                       name="password">
                            </div>
                        </div>
                        <!-- Sign In Button -->
                        <div class="form-group">
                            <div class="col-lg-8 col-lg-offset-2">
                                <div class="card--buttons">
                                    <button type="submit" id="signin-btn" data-behavior="submitForm"
                                            name="AccountSignIn" class="btn btn-primary btn-lg btn-block">
                                        Sign In
                                    </button>
                                </div>
                            </div>
                        </div>
                        <!-- Error Handling -->
                        {% if error %}
                        <div class="error">
                            <p>There was an error: {{ error }}</p>
                        </div>
                        {% endif %}
                        {% if access_token %}
                        <div>
                            <p>Access Token: {{ access_token }}</p>

                            <p>Refresh Token: {{ refresh_token }}</p>
                        </div>
                        {% endif %}
                        <!-- Password Reset -->
                        <div>
                            <div id="gam-forgot-password" class="card--message col-lg-8 col-lg-offset-3">
                                Forgot your password? <a href="{% url 'accounts:password_reset' %}" id="recoverPassword"
                                                         class="link link-grayDarkest link-underline"
                                                         alt="Reset password">Click here</a>
                            </div>
                        </div>
                    </fieldset>
                </form>
                <a href="{% url 'accounts:register' %}">
                    <button class="btn btn-primary btn-lg btn-block"> Create Account </button>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}